packages:
  - playground

allowBuilds:
  '@playwright/browser-chromium': true
  '@vscode/vsce-sign': true
  keytar: true

minimumReleaseAge: 0

patchedDependencies:
  vscode-ext-gen@1.6.0: patches/vscode-ext-gen@1.6.0.patch
