import { defineExtension } from 'reactive-vscode'
import { version } from '../package.json'
import { useBeaconCodeLens } from './composables/use-beacon-codelens'
import { useBeaconCommands } from './composables/use-beacon-commands'
import { useBeaconDiagnostics } from './composables/use-beacon-diagnostics'
import { useBeaconExplorer } from './composables/use-beacon-explorer'
import { useBeaconGit } from './composables/use-beacon-git'
import { useBeaconHighlight } from './composables/use-beacon-highlight'
import { useBeaconHover } from './composables/use-beacon-hover'
import { useBeaconLanguageModelTools } from './composables/use-beacon-language-model-tools'
import { useBeaconNotebook } from './composables/use-beacon-notebook'
import { useBeaconSourceControl } from './composables/use-beacon-source-control'
import { useWorkspaceScan } from './composables/use-workspace-scan'
import { logger } from './utils/logger'

/**
 * VS Code extension lifecycle hooks generated by reactive-vscode.
 */
const { activate, deactivate } = defineExtension(context => {
  useBeaconCommands(context.workspaceState)
  useBeaconDiagnostics()
  const beaconGit = useBeaconGit()
  useBeaconExplorer(beaconGit)
  useWorkspaceScan()
  const beaconHighlight = useBeaconHighlight()
  useBeaconNotebook(beaconHighlight.scanTextDocument)
  useBeaconHover(beaconGit.getMetadata)
  useBeaconSourceControl(beaconGit)
  useBeaconCodeLens()
  useBeaconLanguageModelTools()

  logger.info(`✅ Activated, version: ${version} `)
})

export { activate, deactivate }
