import { defineExtension } from 'reactive-vscode'
import { version } from '../package.json'
import { useBeaconCodeLens } from './composables/use-beacon-codelens'
import { useBeaconCommands } from './composables/use-beacon-commands'
import { useBeaconDiagnostics } from './composables/use-beacon-diagnostics'
import { useBeaconExplorer } from './composables/use-beacon-explorer'
import { useBeaconHighlight } from './composables/use-beacon-highlight'
import { useBeaconHover } from './composables/use-beacon-hover'
import { useWorkspaceScan } from './composables/use-workspace-scan'
import { logger } from './utils/logger'

/**
 * VS Code extension lifecycle hooks generated by reactive-vscode.
 */
const { activate, deactivate } = defineExtension(() => {
  useBeaconCommands()
  useBeaconDiagnostics()
  useBeaconExplorer()
  useWorkspaceScan()
  useBeaconHighlight()
  useBeaconHover()
  useBeaconCodeLens()

  logger.info(`✅ Activated, version: ${version} `)
})

export { activate, deactivate }
