// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-code-beacon"
export const version = "0.0.0"
export const displayName = "Code Beacon"
export const description = "Highlight, list, diagnose, and export code annotations such as TODO, FIXME, BUG, NOTE, REVIEW, SECURITY, and PERF."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "code-beacon.enable"
  | "code-beacon.disable"
  | "code-beacon.toggle"
  | "code-beacon.refresh"
  | "code-beacon.scanWorkspace"
  | "code-beacon.scanActiveFile"
  | "code-beacon.scanOpenEditors"
  | "code-beacon.focusExplorer"
  | "code-beacon.reveal"
  | "code-beacon.copyLink"
  | "code-beacon.copyMarkdown"
  | "code-beacon.createIssue"
  | "code-beacon.resolve"
  | "code-beacon.unresolve"
  | "code-beacon.ignore"
  | "code-beacon.unignore"
  | "code-beacon.exportMarkdown"
  | "code-beacon.exportJson"
  | "code-beacon.exportCsv"
  | "code-beacon.openSettings"
  | "code-beacon.clearCache"

/**
 * Commands map registered by `ntnyq.vscode-code-beacon`
 */
export const commands = {
  /**
   * Enable Code Beacon
   * @value `code-beacon.enable`
   */
  enable: "code-beacon.enable",
  /**
   * Disable Code Beacon
   * @value `code-beacon.disable`
   */
  disable: "code-beacon.disable",
  /**
   * Toggle Code Beacon
   * @value `code-beacon.toggle`
   */
  toggle: "code-beacon.toggle",
  /**
   * Refresh Beacons
   * @value `code-beacon.refresh`
   */
  refresh: "code-beacon.refresh",
  /**
   * Scan Workspace for Beacons
   * @value `code-beacon.scanWorkspace`
   */
  scanWorkspace: "code-beacon.scanWorkspace",
  /**
   * Scan Active File for Beacons
   * @value `code-beacon.scanActiveFile`
   */
  scanActiveFile: "code-beacon.scanActiveFile",
  /**
   * Scan Open Editors for Beacons
   * @value `code-beacon.scanOpenEditors`
   */
  scanOpenEditors: "code-beacon.scanOpenEditors",
  /**
   * Focus Code Beacon Explorer
   * @value `code-beacon.focusExplorer`
   */
  focusExplorer: "code-beacon.focusExplorer",
  /**
   * Reveal Beacon
   * @value `code-beacon.reveal`
   */
  reveal: "code-beacon.reveal",
  /**
   * Copy Beacon Link
   * @value `code-beacon.copyLink`
   */
  copyLink: "code-beacon.copyLink",
  /**
   * Copy Beacon as Markdown
   * @value `code-beacon.copyMarkdown`
   */
  copyMarkdown: "code-beacon.copyMarkdown",
  /**
   * Create Issue Body
   * @value `code-beacon.createIssue`
   */
  createIssue: "code-beacon.createIssue",
  /**
   * Resolve Beacon
   * @value `code-beacon.resolve`
   */
  resolve: "code-beacon.resolve",
  /**
   * Reopen Beacon
   * @value `code-beacon.unresolve`
   */
  unresolve: "code-beacon.unresolve",
  /**
   * Ignore Beacon
   * @value `code-beacon.ignore`
   */
  ignore: "code-beacon.ignore",
  /**
   * Unignore Beacon
   * @value `code-beacon.unignore`
   */
  unignore: "code-beacon.unignore",
  /**
   * Export Beacons as Markdown
   * @value `code-beacon.exportMarkdown`
   */
  exportMarkdown: "code-beacon.exportMarkdown",
  /**
   * Export Beacons as JSON
   * @value `code-beacon.exportJson`
   */
  exportJson: "code-beacon.exportJson",
  /**
   * Export Beacons as CSV
   * @value `code-beacon.exportCsv`
   */
  exportCsv: "code-beacon.exportCsv",
  /**
   * Open Code Beacon Settings
   * @value `code-beacon.openSettings`
   */
  openSettings: "code-beacon.openSettings",
  /**
   * Clear Code Beacon Cache
   * @value `code-beacon.clearCache`
   */
  clearCache: "code-beacon.clearCache",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "code-beacon.enable"
  | "code-beacon.languages"
  | "code-beacon.rules"
  | "code-beacon.include"
  | "code-beacon.exclude"
  | "code-beacon.respectFilesExclude"
  | "code-beacon.respectSearchExclude"
  | "code-beacon.maxFileSize"
  | "code-beacon.maxFilesForSearch"
  | "code-beacon.scanMode"
  | "code-beacon.commentOnly"
  | "code-beacon.decorations.enabled"
  | "code-beacon.diagnostics.mode"
  | "code-beacon.explorer.enabled"
  | "code-beacon.explorer.groupBy"
  | "code-beacon.explorer.scope"
  | "code-beacon.explorer.categories"
  | "code-beacon.explorer.severities"
  | "code-beacon.explorer.owners"
  | "code-beacon.explorer.query"
  | "code-beacon.explorer.includeResolved"
  | "code-beacon.explorer.includeIgnored"
  | "code-beacon.explorer.onlyStale"
  | "code-beacon.explorer.onlyOwnerless"
  | "code-beacon.git.staleDays"
  | "code-beacon.git.showMetadata"
  | "code-beacon.scm.enabled"
  | "code-beacon.codelens.enabled"
  | "code-beacon.hover.enabled"

export interface ConfigKeyTypeMap {
  "code-beacon.enable": boolean,
  "code-beacon.languages": string[],
  "code-beacon.rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  "code-beacon.include": string[],
  "code-beacon.exclude": string[],
  "code-beacon.respectFilesExclude": boolean,
  "code-beacon.respectSearchExclude": boolean,
  "code-beacon.maxFileSize": number,
  "code-beacon.maxFilesForSearch": number,
  "code-beacon.scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  "code-beacon.commentOnly": boolean,
  "code-beacon.decorations.enabled": boolean,
  "code-beacon.diagnostics.mode": ("off" | "openFiles" | "workspace"),
  "code-beacon.explorer.enabled": boolean,
  "code-beacon.explorer.groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
  "code-beacon.explorer.scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
  "code-beacon.explorer.categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
  "code-beacon.explorer.severities": ("hint" | "information" | "warning" | "error")[],
  "code-beacon.explorer.owners": string[],
  "code-beacon.explorer.query": string,
  "code-beacon.explorer.includeResolved": boolean,
  "code-beacon.explorer.includeIgnored": boolean,
  "code-beacon.explorer.onlyStale": boolean,
  "code-beacon.explorer.onlyOwnerless": boolean,
  "code-beacon.git.staleDays": unknown,
  "code-beacon.git.showMetadata": boolean,
  "code-beacon.scm.enabled": boolean,
  "code-beacon.codelens.enabled": boolean,
  "code-beacon.hover.enabled": boolean,
}

export interface ConfigShorthandMap {
  enable: "code-beacon.enable",
  languages: "code-beacon.languages",
  rules: "code-beacon.rules",
  include: "code-beacon.include",
  exclude: "code-beacon.exclude",
  respectFilesExclude: "code-beacon.respectFilesExclude",
  respectSearchExclude: "code-beacon.respectSearchExclude",
  maxFileSize: "code-beacon.maxFileSize",
  maxFilesForSearch: "code-beacon.maxFilesForSearch",
  scanMode: "code-beacon.scanMode",
  commentOnly: "code-beacon.commentOnly",
  decorationsEnabled: "code-beacon.decorations.enabled",
  diagnosticsMode: "code-beacon.diagnostics.mode",
  explorerEnabled: "code-beacon.explorer.enabled",
  explorerGroupBy: "code-beacon.explorer.groupBy",
  explorerScope: "code-beacon.explorer.scope",
  explorerCategories: "code-beacon.explorer.categories",
  explorerSeverities: "code-beacon.explorer.severities",
  explorerOwners: "code-beacon.explorer.owners",
  explorerQuery: "code-beacon.explorer.query",
  explorerIncludeResolved: "code-beacon.explorer.includeResolved",
  explorerIncludeIgnored: "code-beacon.explorer.includeIgnored",
  explorerOnlyStale: "code-beacon.explorer.onlyStale",
  explorerOnlyOwnerless: "code-beacon.explorer.onlyOwnerless",
  gitStaleDays: "code-beacon.git.staleDays",
  gitShowMetadata: "code-beacon.git.showMetadata",
  scmEnabled: "code-beacon.scm.enabled",
  codelensEnabled: "code-beacon.codelens.enabled",
  hoverEnabled: "code-beacon.hover.enabled",
}

export interface ConfigShorthandTypeMap {
  enable: boolean,
  languages: string[],
  rules: { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  include: string[],
  exclude: string[],
  respectFilesExclude: boolean,
  respectSearchExclude: boolean,
  maxFileSize: number,
  maxFilesForSearch: number,
  scanMode: ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  commentOnly: boolean,
  decorationsEnabled: boolean,
  diagnosticsMode: ("off" | "openFiles" | "workspace"),
  explorerEnabled: boolean,
  explorerGroupBy: ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
  explorerScope: ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
  explorerCategories: ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
  explorerSeverities: ("hint" | "information" | "warning" | "error")[],
  explorerOwners: string[],
  explorerQuery: string,
  explorerIncludeResolved: boolean,
  explorerIncludeIgnored: boolean,
  explorerOnlyStale: boolean,
  explorerOnlyOwnerless: boolean,
  gitStaleDays: unknown,
  gitShowMetadata: boolean,
  scmEnabled: boolean,
  codelensEnabled: boolean,
  hoverEnabled: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.vscode-code-beacon`
 */
export const configs = {
  /**
   * Enable or disable code beacon.
   * @key `code-beacon.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "code-beacon.enable",
    default: true,
  } as ConfigItem<"code-beacon.enable">,
  /**
   * Language IDs where annotations are scanned. Use '*' for all languages and prefix with '!' to exclude.
   * @key `code-beacon.languages`
   * @default `["*"]`
   * @type `array`
   */
  languages: {
    key: "code-beacon.languages",
    default: ["*"],
  } as ConfigItem<"code-beacon.languages">,
  /**
   * Custom annotation rules. Built-in rules are enabled unless a custom rule with the same id overrides them.
   * @key `code-beacon.rules`
   * @default `[]`
   * @type `array`
   */
  rules: {
    key: "code-beacon.rules",
    default: [],
  } as ConfigItem<"code-beacon.rules">,
  /**
   * Glob patterns that define files to scan.
   * @key `code-beacon.include`
   * @default `["**\/*"]`
   * @type `array`
   */
  include: {
    key: "code-beacon.include",
    default: ["**/*"],
  } as ConfigItem<"code-beacon.include">,
  /**
   * Glob patterns that define files and folders to exclude from workspace scans.
   * @key `code-beacon.exclude`
   * @default `["**\/node_modules/**","**\/bower_components/**","**\/dist/**","**\/build/**","**\/.git/**","**\/.vscode/**","**\/.vscode-test/**","**\/.github/**","**\/.next/**","**\/coverage/**","**\/*.min.*","**\/*.map","**\/pnpm-lock.yaml","**\/package-lock.json","**\/yarn.lock"]`
   * @type `array`
   */
  exclude: {
    key: "code-beacon.exclude",
    default: ["**/node_modules/**","**/bower_components/**","**/dist/**","**/build/**","**/.git/**","**/.vscode/**","**/.vscode-test/**","**/.github/**","**/.next/**","**/coverage/**","**/*.min.*","**/*.map","**/pnpm-lock.yaml","**/package-lock.json","**/yarn.lock"],
  } as ConfigItem<"code-beacon.exclude">,
  /**
   * Respect VS Code files.exclude during workspace scans.
   * @key `code-beacon.respectFilesExclude`
   * @default `true`
   * @type `boolean`
   */
  respectFilesExclude: {
    key: "code-beacon.respectFilesExclude",
    default: true,
  } as ConfigItem<"code-beacon.respectFilesExclude">,
  /**
   * Respect VS Code search.exclude during workspace scans.
   * @key `code-beacon.respectSearchExclude`
   * @default `true`
   * @type `boolean`
   */
  respectSearchExclude: {
    key: "code-beacon.respectSearchExclude",
    default: true,
  } as ConfigItem<"code-beacon.respectSearchExclude">,
  /**
   * Maximum document text length, in characters, to scan. Set to 0 to disable this size limit.
   * @key `code-beacon.maxFileSize`
   * @default `1000000`
   * @type `number`
   */
  maxFileSize: {
    key: "code-beacon.maxFileSize",
    default: 1000000,
  } as ConfigItem<"code-beacon.maxFileSize">,
  /**
   * Maximum number of files to scan during workspace scans.
   * @key `code-beacon.maxFilesForSearch`
   * @default `5000`
   * @type `number`
   */
  maxFilesForSearch: {
    key: "code-beacon.maxFilesForSearch",
    default: 5000,
  } as ConfigItem<"code-beacon.maxFilesForSearch">,
  /**
   * Default scan mode for Code Beacon.
   * @key `code-beacon.scanMode`
   * @default `"visibleEditors"`
   * @type `string`
   */
  scanMode: {
    key: "code-beacon.scanMode",
    default: "visibleEditors",
  } as ConfigItem<"code-beacon.scanMode">,
  /**
   * Prefer scanning comments only when Code Beacon knows the language comment syntax.
   * @key `code-beacon.commentOnly`
   * @default `true`
   * @type `boolean`
   */
  commentOnly: {
    key: "code-beacon.commentOnly",
    default: true,
  } as ConfigItem<"code-beacon.commentOnly">,
  /**
   * Show editor decorations for annotations.
   * @key `code-beacon.decorations.enabled`
   * @default `true`
   * @type `boolean`
   */
  decorationsEnabled: {
    key: "code-beacon.decorations.enabled",
    default: true,
  } as ConfigItem<"code-beacon.decorations.enabled">,
  /**
   * Controls Problems integration.
   * @key `code-beacon.diagnostics.mode`
   * @default `"off"`
   * @type `string`
   */
  diagnosticsMode: {
    key: "code-beacon.diagnostics.mode",
    default: "off",
  } as ConfigItem<"code-beacon.diagnostics.mode">,
  /**
   * Enable the Code Beacon TreeView.
   * @key `code-beacon.explorer.enabled`
   * @default `true`
   * @type `boolean`
   */
  explorerEnabled: {
    key: "code-beacon.explorer.enabled",
    default: true,
  } as ConfigItem<"code-beacon.explorer.enabled">,
  /**
   * Default grouping mode for the Code Beacon TreeView.
   * @key `code-beacon.explorer.groupBy`
   * @default `"file"`
   * @type `string`
   */
  explorerGroupBy: {
    key: "code-beacon.explorer.groupBy",
    default: "file",
  } as ConfigItem<"code-beacon.explorer.groupBy">,
  /**
   * Limits Code Beacon Explorer results to the workspace, active file, visible editors, or changed files. When set to "changedFiles", the Explorer includes files reported by VS Code's built-in Git extension as staged, unstaged, merge-conflict, or untracked changes. This scope is available only for trusted local desktop workspaces; unavailable Git data, virtual filesystems, and untrusted workspaces produce an empty changed-files view.
   * @key `code-beacon.explorer.scope`
   * @default `"workspace"`
   * @type `string`
   */
  explorerScope: {
    key: "code-beacon.explorer.scope",
    default: "workspace",
  } as ConfigItem<"code-beacon.explorer.scope">,
  /**
   * Categories shown in the Code Beacon Explorer. Leave empty to show all categories.
   * @key `code-beacon.explorer.categories`
   * @default `[]`
   * @type `array`
   */
  explorerCategories: {
    key: "code-beacon.explorer.categories",
    default: [],
  } as ConfigItem<"code-beacon.explorer.categories">,
  /**
   * Severities shown in the Code Beacon Explorer. Leave empty to show all severities.
   * @key `code-beacon.explorer.severities`
   * @default `[]`
   * @type `array`
   */
  explorerSeverities: {
    key: "code-beacon.explorer.severities",
    default: [],
  } as ConfigItem<"code-beacon.explorer.severities">,
  /**
   * Owners shown in the Code Beacon Explorer. Leave empty to show all owners.
   * @key `code-beacon.explorer.owners`
   * @default `[]`
   * @type `array`
   */
  explorerOwners: {
    key: "code-beacon.explorer.owners",
    default: [],
  } as ConfigItem<"code-beacon.explorer.owners">,
  /**
   * Case-insensitive text query for Code Beacon Explorer results.
   * @key `code-beacon.explorer.query`
   * @default `""`
   * @type `string`
   */
  explorerQuery: {
    key: "code-beacon.explorer.query",
    default: "",
  } as ConfigItem<"code-beacon.explorer.query">,
  /**
   * Show resolved beacons in the Code Beacon Explorer.
   * @key `code-beacon.explorer.includeResolved`
   * @default `false`
   * @type `boolean`
   */
  explorerIncludeResolved: {
    key: "code-beacon.explorer.includeResolved",
    default: false,
  } as ConfigItem<"code-beacon.explorer.includeResolved">,
  /**
   * Show ignored beacons in the Code Beacon Explorer.
   * @key `code-beacon.explorer.includeIgnored`
   * @default `false`
   * @type `boolean`
   */
  explorerIncludeIgnored: {
    key: "code-beacon.explorer.includeIgnored",
    default: false,
  } as ConfigItem<"code-beacon.explorer.includeIgnored">,
  /**
   * Show only beacons with a valid Git commit date older than the configured stale threshold.
   * @key `code-beacon.explorer.onlyStale`
   * @default `false`
   * @type `boolean`
   */
  explorerOnlyStale: {
    key: "code-beacon.explorer.onlyStale",
    default: false,
  } as ConfigItem<"code-beacon.explorer.onlyStale">,
  /**
   * Show only beacons with no explicit owner or a whitespace-only owner. Git authors do not implicitly assign a beacon.
   * @key `code-beacon.explorer.onlyOwnerless`
   * @default `false`
   * @type `boolean`
   */
  explorerOnlyOwnerless: {
    key: "code-beacon.explorer.onlyOwnerless",
    default: false,
  } as ConfigItem<"code-beacon.explorer.onlyOwnerless">,
  /**
   * Number of days after which a valid Git commit date is considered stale.
   * @key `code-beacon.git.staleDays`
   * @default `90`
   * @type `integer`
   */
  gitStaleDays: {
    key: "code-beacon.git.staleDays",
    default: 90,
  } as ConfigItem<"code-beacon.git.staleDays">,
  /**
   * Show Git author, age, and commit details in Code Beacon Explorer items. This uses VS Code's built-in Git extension only in trusted local desktop workspaces; unavailable Git data and virtual filesystems show no Git metadata.
   * @key `code-beacon.git.showMetadata`
   * @default `false`
   * @type `boolean`
   */
  gitShowMetadata: {
    key: "code-beacon.git.showMetadata",
    default: false,
  } as ConfigItem<"code-beacon.git.showMetadata">,
  /**
   * Show a read-only Code Beacon Source Control provider for changed Git files containing annotations. It never stages, unstages, commits, or modifies Git; unavailable Git data, virtual filesystems, and untrusted workspaces produce an empty list.
   * @key `code-beacon.scm.enabled`
   * @default `false`
   * @type `boolean`
   */
  scmEnabled: {
    key: "code-beacon.scm.enabled",
    default: false,
  } as ConfigItem<"code-beacon.scm.enabled">,
  /**
   * Enable CodeLens actions above annotation lines.
   * @key `code-beacon.codelens.enabled`
   * @default `false`
   * @type `boolean`
   */
  codelensEnabled: {
    key: "code-beacon.codelens.enabled",
    default: false,
  } as ConfigItem<"code-beacon.codelens.enabled">,
  /**
   * Enable hover details for annotations.
   * @key `code-beacon.hover.enabled`
   * @default `true`
   * @type `boolean`
   */
  hoverEnabled: {
    key: "code-beacon.hover.enabled",
    default: true,
  } as ConfigItem<"code-beacon.hover.enabled">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
  "languages": string[],
  "rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  "include": string[],
  "exclude": string[],
  "respectFilesExclude": boolean,
  "respectSearchExclude": boolean,
  "maxFileSize": number,
  "maxFilesForSearch": number,
  "scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  "commentOnly": boolean,
  "decorations.enabled": boolean,
  "diagnostics.mode": ("off" | "openFiles" | "workspace"),
  "explorer.enabled": boolean,
  "explorer.groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
  "explorer.scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
  "explorer.categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
  "explorer.severities": ("hint" | "information" | "warning" | "error")[],
  "explorer.owners": string[],
  "explorer.query": string,
  "explorer.includeResolved": boolean,
  "explorer.includeIgnored": boolean,
  "explorer.onlyStale": boolean,
  "explorer.onlyOwnerless": boolean,
  "git.staleDays": unknown,
  "git.showMetadata": boolean,
  "scm.enabled": boolean,
  "codelens.enabled": boolean,
  "hover.enabled": boolean,
}

export const scopedConfigs = {
  scope: "code-beacon",
  defaults: {
    "enable": true,
    "languages": ["*"],
    "rules": [],
    "include": ["**/*"],
    "exclude": ["**/node_modules/**","**/bower_components/**","**/dist/**","**/build/**","**/.git/**","**/.vscode/**","**/.vscode-test/**","**/.github/**","**/.next/**","**/coverage/**","**/*.min.*","**/*.map","**/pnpm-lock.yaml","**/package-lock.json","**/yarn.lock"],
    "respectFilesExclude": true,
    "respectSearchExclude": true,
    "maxFileSize": 1000000,
    "maxFilesForSearch": 5000,
    "scanMode": "visibleEditors",
    "commentOnly": true,
    "decorations.enabled": true,
    "diagnostics.mode": "off",
    "explorer.enabled": true,
    "explorer.groupBy": "file",
    "explorer.scope": "workspace",
    "explorer.categories": [],
    "explorer.severities": [],
    "explorer.owners": [],
    "explorer.query": "",
    "explorer.includeResolved": false,
    "explorer.includeIgnored": false,
    "explorer.onlyStale": false,
    "explorer.onlyOwnerless": false,
    "git.staleDays": 90,
    "git.showMetadata": false,
    "scm.enabled": false,
    "codelens.enabled": false,
    "hover.enabled": true,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "code-beacon": {
    "enable": boolean,
    "languages": string[],
    "rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
    "include": string[],
    "exclude": string[],
    "respectFilesExclude": boolean,
    "respectSearchExclude": boolean,
    "maxFileSize": number,
    "maxFilesForSearch": number,
    "scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
    "commentOnly": boolean,
    "decorations": {
      "enabled": boolean,
    },
    "diagnostics": {
      "mode": ("off" | "openFiles" | "workspace"),
    },
    "explorer": {
      "enabled": boolean,
      "groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
      "scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
      "categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
      "severities": ("hint" | "information" | "warning" | "error")[],
      "owners": string[],
      "query": string,
      "includeResolved": boolean,
      "includeIgnored": boolean,
      "onlyStale": boolean,
      "onlyOwnerless": boolean,
    },
    "git": {
      "staleDays": unknown,
      "showMetadata": boolean,
    },
    "scm": {
      "enabled": boolean,
    },
    "codelens": {
      "enabled": boolean,
    },
    "hover": {
      "enabled": boolean,
    },
  },
}

export interface NestedScopedConfigs {
  "enable": boolean,
  "languages": string[],
  "rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  "include": string[],
  "exclude": string[],
  "respectFilesExclude": boolean,
  "respectSearchExclude": boolean,
  "maxFileSize": number,
  "maxFilesForSearch": number,
  "scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  "commentOnly": boolean,
  "decorations": {
    "enabled": boolean,
  },
  "diagnostics": {
    "mode": ("off" | "openFiles" | "workspace"),
  },
  "explorer": {
    "enabled": boolean,
    "groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
    "scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
    "categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
    "severities": ("hint" | "information" | "warning" | "error")[],
    "owners": string[],
    "query": string,
    "includeResolved": boolean,
    "includeIgnored": boolean,
    "onlyStale": boolean,
    "onlyOwnerless": boolean,
  },
  "git": {
    "staleDays": unknown,
    "showMetadata": boolean,
  },
  "scm": {
    "enabled": boolean,
  },
  "codelens": {
    "enabled": boolean,
  },
  "hover": {
    "enabled": boolean,
  },
}
