// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-code-beacon"
export const version = "0.0.0"
export const displayName = "Code Beacon"
export const description = undefined
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "code-beacon.enable"
  | "code-beacon.disable"

/**
 * Commands map registered by `ntnyq.vscode-code-beacon`
 */
export const commands = {
  /**
   * Enable Code Beacon
   * @value `code-beacon.enable`
   */
  enable: "code-beacon.enable",
  /**
   * Disable Code Beacon
   * @value `code-beacon.disable`
   */
  disable: "code-beacon.disable",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "code-beacon.enable"
  | "code-beacon.debug"

export interface ConfigKeyTypeMap {
  "code-beacon.enable": boolean,
  "code-beacon.debug": boolean,
}

export interface ConfigShorthandMap {
  enable: "code-beacon.enable",
  debug: "code-beacon.debug",
}

export interface ConfigShorthandTypeMap {
  enable: boolean,
  debug: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.vscode-code-beacon`
 */
export const configs = {
  /**
   * Enable or disable code beacon.
   * @key `code-beacon.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "code-beacon.enable",
    default: true,
  } as ConfigItem<"code-beacon.enable">,
  /**
   * Enable debug logging.
   * @key `code-beacon.debug`
   * @default `false`
   * @type `boolean`
   */
  debug: {
    key: "code-beacon.debug",
    default: false,
  } as ConfigItem<"code-beacon.debug">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
  "debug": boolean,
}

export const scopedConfigs = {
  scope: "code-beacon",
  defaults: {
    "enable": true,
    "debug": false,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "code-beacon": {
    "enable": boolean,
    "debug": boolean,
  },
}

export interface NestedScopedConfigs {
  "enable": boolean,
  "debug": boolean,
}

