// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "annopulse"
export const version = "0.1.1"
export const displayName = "AnnoPulse"
export const description = "Highlight, list, diagnose, and export code annotations such as TODO, FIXME, BUG, NOTE, REVIEW, SECURITY, and PERF."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "annopulse.enable"
  | "annopulse.disable"
  | "annopulse.toggle"
  | "annopulse.refresh"
  | "annopulse.scanWorkspace"
  | "annopulse.scanActiveFile"
  | "annopulse.scanOpenEditors"
  | "annopulse.focusExplorer"
  | "annopulse.reveal"
  | "annopulse.copyLink"
  | "annopulse.copyMarkdown"
  | "annopulse.createIssue"
  | "annopulse.explain"
  | "annopulse.generateFix"
  | "annopulse.summarizeWorkspace"
  | "annopulse.resolve"
  | "annopulse.unresolve"
  | "annopulse.ignore"
  | "annopulse.unignore"
  | "annopulse.exportMarkdown"
  | "annopulse.exportJson"
  | "annopulse.exportCsv"
  | "annopulse.openSettings"
  | "annopulse.clearCache"

/**
 * Commands map registered by `ntnyq.annopulse`
 */
export const commands = {
  /**
   * Enable AnnoPulse
   * @value `annopulse.enable`
   */
  enable: "annopulse.enable",
  /**
   * Disable AnnoPulse
   * @value `annopulse.disable`
   */
  disable: "annopulse.disable",
  /**
   * Toggle AnnoPulse
   * @value `annopulse.toggle`
   */
  toggle: "annopulse.toggle",
  /**
   * Refresh Annotations
   * @value `annopulse.refresh`
   */
  refresh: "annopulse.refresh",
  /**
   * Scan Workspace for Annotations
   * @value `annopulse.scanWorkspace`
   */
  scanWorkspace: "annopulse.scanWorkspace",
  /**
   * Scan Active File for Annotations
   * @value `annopulse.scanActiveFile`
   */
  scanActiveFile: "annopulse.scanActiveFile",
  /**
   * Scan Open Editors for Annotations
   * @value `annopulse.scanOpenEditors`
   */
  scanOpenEditors: "annopulse.scanOpenEditors",
  /**
   * Focus AnnoPulse Explorer
   * @value `annopulse.focusExplorer`
   */
  focusExplorer: "annopulse.focusExplorer",
  /**
   * Reveal Annotation
   * @value `annopulse.reveal`
   */
  reveal: "annopulse.reveal",
  /**
   * Copy Annotation Link
   * @value `annopulse.copyLink`
   */
  copyLink: "annopulse.copyLink",
  /**
   * Copy Annotation as Markdown
   * @value `annopulse.copyMarkdown`
   */
  copyMarkdown: "annopulse.copyMarkdown",
  /**
   * Create Issue Body
   * @value `annopulse.createIssue`
   */
  createIssue: "annopulse.createIssue",
  /**
   * Explain Annotation
   * @value `annopulse.explain`
   */
  explain: "annopulse.explain",
  /**
   * Generate Annotation Fix
   * @value `annopulse.generateFix`
   */
  generateFix: "annopulse.generateFix",
  /**
   * Summarize Workspace Annotations
   * @value `annopulse.summarizeWorkspace`
   */
  summarizeWorkspace: "annopulse.summarizeWorkspace",
  /**
   * Resolve Annotation
   * @value `annopulse.resolve`
   */
  resolve: "annopulse.resolve",
  /**
   * Reopen Annotation
   * @value `annopulse.unresolve`
   */
  unresolve: "annopulse.unresolve",
  /**
   * Ignore Annotation
   * @value `annopulse.ignore`
   */
  ignore: "annopulse.ignore",
  /**
   * Unignore Annotation
   * @value `annopulse.unignore`
   */
  unignore: "annopulse.unignore",
  /**
   * Export Annotations as Markdown
   * @value `annopulse.exportMarkdown`
   */
  exportMarkdown: "annopulse.exportMarkdown",
  /**
   * Export Annotations as JSON
   * @value `annopulse.exportJson`
   */
  exportJson: "annopulse.exportJson",
  /**
   * Export Annotations as CSV
   * @value `annopulse.exportCsv`
   */
  exportCsv: "annopulse.exportCsv",
  /**
   * Open AnnoPulse Settings
   * @value `annopulse.openSettings`
   */
  openSettings: "annopulse.openSettings",
  /**
   * Clear AnnoPulse Cache
   * @value `annopulse.clearCache`
   */
  clearCache: "annopulse.clearCache",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "annopulse.enable"
  | "annopulse.languages"
  | "annopulse.rules"
  | "annopulse.include"
  | "annopulse.exclude"
  | "annopulse.respectFilesExclude"
  | "annopulse.respectSearchExclude"
  | "annopulse.maxFileSize"
  | "annopulse.maxFilesForSearch"
  | "annopulse.scanMode"
  | "annopulse.commentOnly"
  | "annopulse.decorations.enabled"
  | "annopulse.diagnostics.mode"
  | "annopulse.explorer.enabled"
  | "annopulse.explorer.groupBy"
  | "annopulse.explorer.scope"
  | "annopulse.explorer.categories"
  | "annopulse.explorer.severities"
  | "annopulse.explorer.owners"
  | "annopulse.explorer.query"
  | "annopulse.explorer.includeResolved"
  | "annopulse.explorer.includeIgnored"
  | "annopulse.explorer.onlyStale"
  | "annopulse.explorer.onlyOwnerless"
  | "annopulse.git.staleDays"
  | "annopulse.git.showMetadata"
  | "annopulse.ai.enabled"
  | "annopulse.scm.enabled"
  | "annopulse.codelens.enabled"
  | "annopulse.hover.enabled"

export interface ConfigKeyTypeMap {
  "annopulse.enable": boolean,
  "annopulse.languages": string[],
  "annopulse.rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  "annopulse.include": string[],
  "annopulse.exclude": string[],
  "annopulse.respectFilesExclude": boolean,
  "annopulse.respectSearchExclude": boolean,
  "annopulse.maxFileSize": number,
  "annopulse.maxFilesForSearch": number,
  "annopulse.scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  "annopulse.commentOnly": boolean,
  "annopulse.decorations.enabled": boolean,
  "annopulse.diagnostics.mode": ("off" | "openFiles" | "workspace"),
  "annopulse.explorer.enabled": boolean,
  "annopulse.explorer.groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
  "annopulse.explorer.scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
  "annopulse.explorer.categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
  "annopulse.explorer.severities": ("hint" | "information" | "warning" | "error")[],
  "annopulse.explorer.owners": string[],
  "annopulse.explorer.query": string,
  "annopulse.explorer.includeResolved": boolean,
  "annopulse.explorer.includeIgnored": boolean,
  "annopulse.explorer.onlyStale": boolean,
  "annopulse.explorer.onlyOwnerless": boolean,
  "annopulse.git.staleDays": unknown,
  "annopulse.git.showMetadata": boolean,
  "annopulse.ai.enabled": boolean,
  "annopulse.scm.enabled": boolean,
  "annopulse.codelens.enabled": boolean,
  "annopulse.hover.enabled": boolean,
}

export interface ConfigShorthandMap {
  enable: "annopulse.enable",
  languages: "annopulse.languages",
  rules: "annopulse.rules",
  include: "annopulse.include",
  exclude: "annopulse.exclude",
  respectFilesExclude: "annopulse.respectFilesExclude",
  respectSearchExclude: "annopulse.respectSearchExclude",
  maxFileSize: "annopulse.maxFileSize",
  maxFilesForSearch: "annopulse.maxFilesForSearch",
  scanMode: "annopulse.scanMode",
  commentOnly: "annopulse.commentOnly",
  decorationsEnabled: "annopulse.decorations.enabled",
  diagnosticsMode: "annopulse.diagnostics.mode",
  explorerEnabled: "annopulse.explorer.enabled",
  explorerGroupBy: "annopulse.explorer.groupBy",
  explorerScope: "annopulse.explorer.scope",
  explorerCategories: "annopulse.explorer.categories",
  explorerSeverities: "annopulse.explorer.severities",
  explorerOwners: "annopulse.explorer.owners",
  explorerQuery: "annopulse.explorer.query",
  explorerIncludeResolved: "annopulse.explorer.includeResolved",
  explorerIncludeIgnored: "annopulse.explorer.includeIgnored",
  explorerOnlyStale: "annopulse.explorer.onlyStale",
  explorerOnlyOwnerless: "annopulse.explorer.onlyOwnerless",
  gitStaleDays: "annopulse.git.staleDays",
  gitShowMetadata: "annopulse.git.showMetadata",
  aiEnabled: "annopulse.ai.enabled",
  scmEnabled: "annopulse.scm.enabled",
  codelensEnabled: "annopulse.codelens.enabled",
  hoverEnabled: "annopulse.hover.enabled",
}

export interface ConfigShorthandTypeMap {
  enable: boolean,
  languages: string[],
  rules: { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  include: string[],
  exclude: string[],
  respectFilesExclude: boolean,
  respectSearchExclude: boolean,
  maxFileSize: number,
  maxFilesForSearch: number,
  scanMode: ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  commentOnly: boolean,
  decorationsEnabled: boolean,
  diagnosticsMode: ("off" | "openFiles" | "workspace"),
  explorerEnabled: boolean,
  explorerGroupBy: ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
  explorerScope: ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
  explorerCategories: ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
  explorerSeverities: ("hint" | "information" | "warning" | "error")[],
  explorerOwners: string[],
  explorerQuery: string,
  explorerIncludeResolved: boolean,
  explorerIncludeIgnored: boolean,
  explorerOnlyStale: boolean,
  explorerOnlyOwnerless: boolean,
  gitStaleDays: unknown,
  gitShowMetadata: boolean,
  aiEnabled: boolean,
  scmEnabled: boolean,
  codelensEnabled: boolean,
  hoverEnabled: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.annopulse`
 */
export const configs = {
  /**
   * Enable or disable AnnoPulse.
   * @key `annopulse.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "annopulse.enable",
    default: true,
  } as ConfigItem<"annopulse.enable">,
  /**
   * Language IDs where annotations are scanned. Use '*' for all languages and prefix with '!' to exclude.
   * @key `annopulse.languages`
   * @default `["*"]`
   * @type `array`
   */
  languages: {
    key: "annopulse.languages",
    default: ["*"],
  } as ConfigItem<"annopulse.languages">,
  /**
   * Custom annotation rules. Built-in rules are enabled unless a custom rule with the same id overrides them.
   * @key `annopulse.rules`
   * @default `[]`
   * @type `array`
   */
  rules: {
    key: "annopulse.rules",
    default: [],
  } as ConfigItem<"annopulse.rules">,
  /**
   * Glob patterns that define files to scan.
   * @key `annopulse.include`
   * @default `["**\/*"]`
   * @type `array`
   */
  include: {
    key: "annopulse.include",
    default: ["**/*"],
  } as ConfigItem<"annopulse.include">,
  /**
   * Glob patterns that define files and folders to exclude from workspace scans.
   * @key `annopulse.exclude`
   * @default `["**\/node_modules/**","**\/bower_components/**","**\/dist/**","**\/build/**","**\/.git/**","**\/.vscode/**","**\/.vscode-test/**","**\/.github/**","**\/.next/**","**\/coverage/**","**\/*.min.*","**\/*.map","**\/pnpm-lock.yaml","**\/package-lock.json","**\/yarn.lock"]`
   * @type `array`
   */
  exclude: {
    key: "annopulse.exclude",
    default: ["**/node_modules/**","**/bower_components/**","**/dist/**","**/build/**","**/.git/**","**/.vscode/**","**/.vscode-test/**","**/.github/**","**/.next/**","**/coverage/**","**/*.min.*","**/*.map","**/pnpm-lock.yaml","**/package-lock.json","**/yarn.lock"],
  } as ConfigItem<"annopulse.exclude">,
  /**
   * Respect VS Code files.exclude during workspace scans.
   * @key `annopulse.respectFilesExclude`
   * @default `true`
   * @type `boolean`
   */
  respectFilesExclude: {
    key: "annopulse.respectFilesExclude",
    default: true,
  } as ConfigItem<"annopulse.respectFilesExclude">,
  /**
   * Respect VS Code search.exclude during workspace scans.
   * @key `annopulse.respectSearchExclude`
   * @default `true`
   * @type `boolean`
   */
  respectSearchExclude: {
    key: "annopulse.respectSearchExclude",
    default: true,
  } as ConfigItem<"annopulse.respectSearchExclude">,
  /**
   * Maximum document text length, in characters, to scan. Set to 0 to disable this size limit.
   * @key `annopulse.maxFileSize`
   * @default `1000000`
   * @type `number`
   */
  maxFileSize: {
    key: "annopulse.maxFileSize",
    default: 1000000,
  } as ConfigItem<"annopulse.maxFileSize">,
  /**
   * Maximum number of files to scan during workspace scans.
   * @key `annopulse.maxFilesForSearch`
   * @default `5000`
   * @type `number`
   */
  maxFilesForSearch: {
    key: "annopulse.maxFilesForSearch",
    default: 5000,
  } as ConfigItem<"annopulse.maxFilesForSearch">,
  /**
   * Default scan mode for AnnoPulse.
   * @key `annopulse.scanMode`
   * @default `"visibleEditors"`
   * @type `string`
   */
  scanMode: {
    key: "annopulse.scanMode",
    default: "visibleEditors",
  } as ConfigItem<"annopulse.scanMode">,
  /**
   * Prefer scanning comments only when AnnoPulse knows the language comment syntax.
   * @key `annopulse.commentOnly`
   * @default `true`
   * @type `boolean`
   */
  commentOnly: {
    key: "annopulse.commentOnly",
    default: true,
  } as ConfigItem<"annopulse.commentOnly">,
  /**
   * Show editor decorations for annotations.
   * @key `annopulse.decorations.enabled`
   * @default `true`
   * @type `boolean`
   */
  decorationsEnabled: {
    key: "annopulse.decorations.enabled",
    default: true,
  } as ConfigItem<"annopulse.decorations.enabled">,
  /**
   * Controls Problems integration.
   * @key `annopulse.diagnostics.mode`
   * @default `"off"`
   * @type `string`
   */
  diagnosticsMode: {
    key: "annopulse.diagnostics.mode",
    default: "off",
  } as ConfigItem<"annopulse.diagnostics.mode">,
  /**
   * Enable the AnnoPulse TreeView.
   * @key `annopulse.explorer.enabled`
   * @default `true`
   * @type `boolean`
   */
  explorerEnabled: {
    key: "annopulse.explorer.enabled",
    default: true,
  } as ConfigItem<"annopulse.explorer.enabled">,
  /**
   * Default grouping mode for the AnnoPulse TreeView.
   * @key `annopulse.explorer.groupBy`
   * @default `"file"`
   * @type `string`
   */
  explorerGroupBy: {
    key: "annopulse.explorer.groupBy",
    default: "file",
  } as ConfigItem<"annopulse.explorer.groupBy">,
  /**
   * Limits AnnoPulse Explorer results to the workspace, active file, visible editors, or changed files. When set to "changedFiles", the Explorer includes files reported by VS Code's built-in Git extension as staged, unstaged, merge-conflict, or untracked changes. This scope is available only for trusted local desktop workspaces; unavailable Git data, virtual filesystems, and untrusted workspaces produce an empty changed-files view.
   * @key `annopulse.explorer.scope`
   * @default `"workspace"`
   * @type `string`
   */
  explorerScope: {
    key: "annopulse.explorer.scope",
    default: "workspace",
  } as ConfigItem<"annopulse.explorer.scope">,
  /**
   * Categories shown in the AnnoPulse Explorer. Leave empty to show all categories.
   * @key `annopulse.explorer.categories`
   * @default `[]`
   * @type `array`
   */
  explorerCategories: {
    key: "annopulse.explorer.categories",
    default: [],
  } as ConfigItem<"annopulse.explorer.categories">,
  /**
   * Severities shown in the AnnoPulse Explorer. Leave empty to show all severities.
   * @key `annopulse.explorer.severities`
   * @default `[]`
   * @type `array`
   */
  explorerSeverities: {
    key: "annopulse.explorer.severities",
    default: [],
  } as ConfigItem<"annopulse.explorer.severities">,
  /**
   * Owners shown in the AnnoPulse Explorer. Leave empty to show all owners.
   * @key `annopulse.explorer.owners`
   * @default `[]`
   * @type `array`
   */
  explorerOwners: {
    key: "annopulse.explorer.owners",
    default: [],
  } as ConfigItem<"annopulse.explorer.owners">,
  /**
   * Case-insensitive text query for AnnoPulse Explorer results.
   * @key `annopulse.explorer.query`
   * @default `""`
   * @type `string`
   */
  explorerQuery: {
    key: "annopulse.explorer.query",
    default: "",
  } as ConfigItem<"annopulse.explorer.query">,
  /**
   * Show resolved annotations in the AnnoPulse Explorer.
   * @key `annopulse.explorer.includeResolved`
   * @default `false`
   * @type `boolean`
   */
  explorerIncludeResolved: {
    key: "annopulse.explorer.includeResolved",
    default: false,
  } as ConfigItem<"annopulse.explorer.includeResolved">,
  /**
   * Show ignored annotations in the AnnoPulse Explorer.
   * @key `annopulse.explorer.includeIgnored`
   * @default `false`
   * @type `boolean`
   */
  explorerIncludeIgnored: {
    key: "annopulse.explorer.includeIgnored",
    default: false,
  } as ConfigItem<"annopulse.explorer.includeIgnored">,
  /**
   * Show only annotations with a valid Git commit date older than the configured stale threshold.
   * @key `annopulse.explorer.onlyStale`
   * @default `false`
   * @type `boolean`
   */
  explorerOnlyStale: {
    key: "annopulse.explorer.onlyStale",
    default: false,
  } as ConfigItem<"annopulse.explorer.onlyStale">,
  /**
   * Show only annotations with no explicit owner or a whitespace-only owner. Git authors do not implicitly assign an annotation.
   * @key `annopulse.explorer.onlyOwnerless`
   * @default `false`
   * @type `boolean`
   */
  explorerOnlyOwnerless: {
    key: "annopulse.explorer.onlyOwnerless",
    default: false,
  } as ConfigItem<"annopulse.explorer.onlyOwnerless">,
  /**
   * Number of days after which a valid Git commit date is considered stale.
   * @key `annopulse.git.staleDays`
   * @default `90`
   * @type `integer`
   */
  gitStaleDays: {
    key: "annopulse.git.staleDays",
    default: 90,
  } as ConfigItem<"annopulse.git.staleDays">,
  /**
   * Show Git author, age, and commit details in AnnoPulse Explorer items. This uses VS Code's built-in Git extension only in trusted local desktop workspaces; unavailable Git data and virtual filesystems show no Git metadata.
   * @key `annopulse.git.showMetadata`
   * @default `false`
   * @type `boolean`
   */
  gitShowMetadata: {
    key: "annopulse.git.showMetadata",
    default: false,
  } as ConfigItem<"annopulse.git.showMetadata">,
  /**
   * Enable AnnoPulse AI features. Read-only Language Model Tools share only already-indexed annotations after confirmation; user-triggered AI commands send only bounded context for a selected annotation or a bounded summary of already-indexed workspace annotations.
   * @key `annopulse.ai.enabled`
   * @default `false`
   * @type `boolean`
   */
  aiEnabled: {
    key: "annopulse.ai.enabled",
    default: false,
  } as ConfigItem<"annopulse.ai.enabled">,
  /**
   * Show a read-only AnnoPulse Source Control provider for changed Git files containing annotations. It never stages, unstages, commits, or modifies Git; unavailable Git data, virtual filesystems, and untrusted workspaces produce an empty list.
   * @key `annopulse.scm.enabled`
   * @default `false`
   * @type `boolean`
   */
  scmEnabled: {
    key: "annopulse.scm.enabled",
    default: false,
  } as ConfigItem<"annopulse.scm.enabled">,
  /**
   * Enable CodeLens actions above annotation lines.
   * @key `annopulse.codelens.enabled`
   * @default `false`
   * @type `boolean`
   */
  codelensEnabled: {
    key: "annopulse.codelens.enabled",
    default: false,
  } as ConfigItem<"annopulse.codelens.enabled">,
  /**
   * Enable hover details for annotations.
   * @key `annopulse.hover.enabled`
   * @default `true`
   * @type `boolean`
   */
  hoverEnabled: {
    key: "annopulse.hover.enabled",
    default: true,
  } as ConfigItem<"annopulse.hover.enabled">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
  "languages": string[],
  "rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  "include": string[],
  "exclude": string[],
  "respectFilesExclude": boolean,
  "respectSearchExclude": boolean,
  "maxFileSize": number,
  "maxFilesForSearch": number,
  "scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  "commentOnly": boolean,
  "decorations.enabled": boolean,
  "diagnostics.mode": ("off" | "openFiles" | "workspace"),
  "explorer.enabled": boolean,
  "explorer.groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
  "explorer.scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
  "explorer.categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
  "explorer.severities": ("hint" | "information" | "warning" | "error")[],
  "explorer.owners": string[],
  "explorer.query": string,
  "explorer.includeResolved": boolean,
  "explorer.includeIgnored": boolean,
  "explorer.onlyStale": boolean,
  "explorer.onlyOwnerless": boolean,
  "git.staleDays": unknown,
  "git.showMetadata": boolean,
  "ai.enabled": boolean,
  "scm.enabled": boolean,
  "codelens.enabled": boolean,
  "hover.enabled": boolean,
}

export const scopedConfigs = {
  scope: "annopulse",
  defaults: {
    "enable": true,
    "languages": ["*"],
    "rules": [],
    "include": ["**/*"],
    "exclude": ["**/node_modules/**","**/bower_components/**","**/dist/**","**/build/**","**/.git/**","**/.vscode/**","**/.vscode-test/**","**/.github/**","**/.next/**","**/coverage/**","**/*.min.*","**/*.map","**/pnpm-lock.yaml","**/package-lock.json","**/yarn.lock"],
    "respectFilesExclude": true,
    "respectSearchExclude": true,
    "maxFileSize": 1000000,
    "maxFilesForSearch": 5000,
    "scanMode": "visibleEditors",
    "commentOnly": true,
    "decorations.enabled": true,
    "diagnostics.mode": "off",
    "explorer.enabled": true,
    "explorer.groupBy": "file",
    "explorer.scope": "workspace",
    "explorer.categories": [],
    "explorer.severities": [],
    "explorer.owners": [],
    "explorer.query": "",
    "explorer.includeResolved": false,
    "explorer.includeIgnored": false,
    "explorer.onlyStale": false,
    "explorer.onlyOwnerless": false,
    "git.staleDays": 90,
    "git.showMetadata": false,
    "ai.enabled": false,
    "scm.enabled": false,
    "codelens.enabled": false,
    "hover.enabled": true,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "annopulse": {
    "enable": boolean,
    "languages": string[],
    "rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
    "include": string[],
    "exclude": string[],
    "respectFilesExclude": boolean,
    "respectSearchExclude": boolean,
    "maxFileSize": number,
    "maxFilesForSearch": number,
    "scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
    "commentOnly": boolean,
    "decorations": {
      "enabled": boolean,
    },
    "diagnostics": {
      "mode": ("off" | "openFiles" | "workspace"),
    },
    "explorer": {
      "enabled": boolean,
      "groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
      "scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
      "categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
      "severities": ("hint" | "information" | "warning" | "error")[],
      "owners": string[],
      "query": string,
      "includeResolved": boolean,
      "includeIgnored": boolean,
      "onlyStale": boolean,
      "onlyOwnerless": boolean,
    },
    "git": {
      "staleDays": unknown,
      "showMetadata": boolean,
    },
    "ai": {
      "enabled": boolean,
    },
    "scm": {
      "enabled": boolean,
    },
    "codelens": {
      "enabled": boolean,
    },
    "hover": {
      "enabled": boolean,
    },
  },
}

export interface NestedScopedConfigs {
  "enable": boolean,
  "languages": string[],
  "rules": { 'id': string; 'label': string; 'category': ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom"); 'enabled'?: boolean; 'matcher': { 'type': ("text" | "regex"); 'value'?: string; 'pattern'?: string; 'flags'?: string; 'caseSensitive'?: boolean; 'wholeWord'?: boolean; 'colon'?: ("required" | "optional" | "forbidden") }; 'severity': ("hint" | "information" | "warning" | "error"); 'commentOnly'?: boolean; 'languages'?: string[]; 'style'?: { 'marker'?: ("keyword" | "message" | "line"); 'color'?: string; 'backgroundColor'?: string; 'border'?: string; 'borderRadius'?: string; 'overviewRulerColor'?: string }; 'diagnostics'?: { 'enabled'?: boolean; 'severity'?: ("hint" | "information" | "warning" | "error") } }[],
  "include": string[],
  "exclude": string[],
  "respectFilesExclude": boolean,
  "respectSearchExclude": boolean,
  "maxFileSize": number,
  "maxFilesForSearch": number,
  "scanMode": ("visibleEditors" | "openEditors" | "workspace" | "manual"),
  "commentOnly": boolean,
  "decorations": {
    "enabled": boolean,
  },
  "diagnostics": {
    "mode": ("off" | "openFiles" | "workspace"),
  },
  "explorer": {
    "enabled": boolean,
    "groupBy": ("file" | "rule" | "category" | "severity" | "owner" | "flat"),
    "scope": ("workspace" | "activeFile" | "openEditors" | "changedFiles"),
    "categories": ("todo" | "fixme" | "bug" | "hack" | "note" | "review" | "security" | "perf" | "question" | "custom")[],
    "severities": ("hint" | "information" | "warning" | "error")[],
    "owners": string[],
    "query": string,
    "includeResolved": boolean,
    "includeIgnored": boolean,
    "onlyStale": boolean,
    "onlyOwnerless": boolean,
  },
  "git": {
    "staleDays": unknown,
    "showMetadata": boolean,
  },
  "ai": {
    "enabled": boolean,
  },
  "scm": {
    "enabled": boolean,
  },
  "codelens": {
    "enabled": boolean,
  },
  "hover": {
    "enabled": boolean,
  },
}
